### ISSUE TITLE
Crashed after moving first Settlers unit

### ISSUE THREAD

**Issue by AlexFolland** [SWY1985/CivOne#347]
Here's the full output from the debug console, though I ran without debugging.  I wish I could run with debugging.  It gives line numbers though, at least.

```
-------------------------------------------------------------------
You may only use the Microsoft .NET Core Debugger (vsdbg) with
Visual Studio Code, Visual Studio or Visual Studio for Mac software
to help you develop and test your applications.
-------------------------------------------------------------------
Game Start
Setting Loaded - FullScreen: 0
Setting Loaded - Scale: 4
Setting Loaded - AspectRatio: 0
Setting Loaded - DebugMenu: 1
Setting Loaded - CursorType: 0
Loaded e:\games\civone\data\sp257.pic
Warning: Character width larger than bytes per character. (ID: 95, Width: 9)
Loaded e:\games\civone\data\iconpg2.pic
Loaded e:\games\civone\data\iconpg3.pic
Loaded e:\games\civone\data\iconpg6.pic
Loaded e:\games\civone\data\iconpg5.pic
Loaded e:\games\civone\data\iconpg1.pic
Loaded e:\games\civone\data\iconpg4.pic
Loaded e:\games\civone\data\iconpg8.pic
Loaded e:\games\civone\data\iconpg7.pic
Loaded e:\games\civone\data\citypix2.pic
Loaded e:\games\civone\data\sp299.pic
Loaded e:\games\civone\data\sp257.pic
Warning: Character width larger than bytes per character. (ID: 95, Width: 9)
Loaded e:\games\civone\data\birth0.pic
Loaded e:\games\civone\data\birth1.pic
Loaded e:\games\civone\data\logo.pic
Checking data files...
- Done, all files exist
Checking data files...
- Done, all files exist
Civilopedia: Preloading articles...
Loaded e:\games\civone\data\iconpg4.pic
Loaded e:\games\civone\data\sp299.pic
Loaded e:\games\civone\data\iconpg5.pic
Loaded e:\games\civone\data\iconpg8.pic
Loaded e:\games\civone\data\iconpg6.pic
Loaded e:\games\civone\data\iconpg1.pic
Loaded e:\games\civone\data\iconpg3.pic
Credits: "A MICROPROSE PRESENTATION"
Loaded e:\games\civone\data\iconpg2.pic
Loaded e:\games\civone\data\iconpg7.pic
Loaded e:\games\civone\data\iconpgd.pic
Loaded e:\games\civone\data\iconpgb.pic
Loaded e:\games\civone\data\iconpga.pic
Loaded e:\games\civone\data\iconpga.pic
Loaded e:\games\civone\data\iconpgb.pic
Loaded e:\games\civone\data\iconpge.pic
Loaded e:\games\civone\data\iconpgd.pic
Loaded e:\games\civone\data\iconpgb.pic
Loaded e:\games\civone\data\iconpgc.pic
Loaded e:\games\civone\data\iconpgd.pic
Loaded e:\games\civone\data\iconpgc.pic
Loaded e:\games\civone\data\iconpgc.pic
Loaded e:\games\civone\data\iconpga.pic
Loaded e:\games\civone\data\iconpgb.pic
Loaded e:\games\civone\data\iconpga.pic
Loaded e:\games\civone\data\iconpge.pic
Loaded e:\games\civone\data\iconpge.pic
Loaded e:\games\civone\data\iconpgc.pic
Loaded e:\games\civone\data\iconpgc.pic
Loaded e:\games\civone\data\iconpga.pic
Loaded e:\games\civone\data\iconpgd.pic
Loaded e:\games\civone\data\iconpge.pic
Loaded e:\games\civone\data\iconpgd.pic
Loaded e:\games\civone\data\iconpgb.pic
Loaded e:\games\civone\data\iconpgd.pic
Loaded e:\games\civone\data\iconpgc.pic
Loaded e:\games\civone\data\iconpga.pic
Loaded e:\games\civone\data\iconpgb.pic
Civilopedia: Preloading done!
Fullscreen mode
Main Menu: Start a New Game
Map instance created
Generating map (Land Mass: 1, Temperature: 1, Climate: 1, Age: 1)
Map: Stage 1 - Generate land mass
Map: Stage 2 - Temperature adjustments
Map: Stage 3 - Merge elevation and latitude into the map
Map: Stage 4 - Climate adjustments
Map: Stage 5 - Age adjustments
Map: Stage 6 - Create rivers
Map: Calculate continent and ocean sizes
Loaded e:\games\civone\data\birth1.pic
Map: Creating poles
Map: Placing goody huts
Map: Calculating land value
Map: Ready
Loaded e:\games\civone\data\birth2.pic
Loaded e:\games\civone\data\birth3.pic
Loaded e:\games\civone\data\birth4.pic
Loaded e:\games\civone\data\birth5.pic
Loaded e:\games\civone\data\birth6.pic
Loaded e:\games\civone\data\birth7.pic
Loaded e:\games\civone\data\birth8.pic
Intro: "In the beginning,"
Loaded e:\games\civone\data\diffs.pic
Difficulty: Emperor (toughest)
Competition: 7 Civilizations
Loaded e:\games\civone\data\slam2.pic
Tribe: Russian
Game instance created (difficulty: 4, competition: 7)
- Player 0 is Atilla of the Barbarians
- Player 1 is Stalin of the Russians (human)
- Player 2 is Shaka of the Zulus
- Player 3 is Frederick of the Germans
- Player 4 is Montezuma of the Aztecs
- Player 5 is Mao Tse Tung of the Chinese
- Player 6 is Elizabeth I of the English
- Player 7 is M.Gandhi of the Indians
Adding starting units...
12
63
34
67
44
13
73
Calculate players handicap...
Apply players bonus...
Turn 0: 4000 BC
Stalin, you have risen
to become leader of the
Russians. May your reign
be long and prosperous.
The Russians have knowledge
of Irrigation, Mining,
Alphabet, and Roads.
Loaded e:\games\civone\data\ter257.pic

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CivOne.Game.UpdateResources(ITile tile, Boolean ownerCities) in e:\games\civone\src\Game.cs:line 353
   at CivOne.Templates.BaseUnit.MoveEnd(Object sender, EventArgs args) in e:\games\civone\src\Templates\BaseUnit.cs:line 387
   at System.EventHandler.Invoke(Object sender, EventArgs e)
   at CivOne.GameTask.EndTask() in e:\games\civone\src\GameTask.cs:line 90
   at CivOne.Tasks.MoveUnit.Step() in e:\games\civone\src\Tasks\MoveUnit.cs:line 40
   at CivOne.GameTask.Update() in e:\games\civone\src\GameTask.cs:line 49
   at CivOne.Window.get_HasUpdate() in e:\games\civone\src\Window.cs:line 102
   at CivOne.Window.OnUpdateFrame(FrameEventArgs args) in e:\games\civone\src\Window.cs:line 296
   at OpenTK.GameWindow.RaiseUpdateFrame(Double elapsed, Double& timestamp)
   at OpenTK.GameWindow.DispatchUpdateAndRenderFrame(Object sender, EventArgs e)
   at OpenTK.GameWindow.Run(Double updates_per_second, Double frames_per_second)
   at CivOne.Program.Main(String[] args) in e:\games\civone\src\Program.cs:line 36
```

**Comment by SWY1985** [comment]
That was a pretty stupid mistake on my part... it's fixed now.
